.gitignore, MetFragLib/src/main/java/de/ipbhalle/metfraglib/database/OnlineForIdentDatabase.java, MetFragLib/src/main/java/de/ipbhalle/metfraglib/functions/ForIdentRestWebService.java, MetFragLib/src/main/java/de/ipbhalle/metfraglib/parameter/ClassNames.java, MetFragLib/src/main/java/de/ipbhalle/metfraglib/parameter/VariableNames.java, MetFragWeb/src/main/java/de/ipbhalle/metfragweb/container/AvailableParameters.java, MetFragWeb/src/main/webapp/includes/candidateFiltersPrime.xhtml, MetFragWeb/src/main/webapp/includes/candidateScoresPrime.xhtml
This PR contains the following: 
- .gitignore entries for IntelliJ IDE
- The URL of FOR-IDENT has been changed causing the Web Service to break
- The Displayed Value for FOR-IDENT has been changed from ForIdent to FOR-IDENT
=> Adjust FOR-IDENT Url and displayed name

.gitignore, Dockerfile, MetFragWeb/pom.xml, README.md
Hi Christoph, we can now build the WAR file from within this project. 
Yours, Steffen
=> Containerize

MetFragWeb/src/main/webapp/includes/footer.xhtml
Update link to MetFrag2010, 
remove decommissioned MetFusion
=> Update tools links

Dockerfile
This PR contains a new MetFrag Dockerfile. The container is based on latest official maven as build environment and official tomcat as webapp server.
It supports:
* JAVA_OPTS="-Xmx?g -Xms?g" to adjust jvm memory
* environment variable WEBPREFIX to adjust the web app name
* automatic use of a metfrag settings file if provided at /resources/settings.properties 
* it integrates a number of textfile libraries
=> Create new MetFrag container

MetFragWeb/pom.xml, MetFragWeb/src/main/java/de/ipbhalle/metfragweb/controller/MetFragWebBean.java
Have an eye towards Travis, looks unhappy at the moment. Yours, Steffen
=> Raise candidate mass limit to 2000, improve error message, closes #43

Dockerfile
Updated MetFrag files to remove bad elements causing formula errors. Tested with MetFragCL and should work. Issues posted: see #47 and #46
Plus merge commit (should not have changed anything).
=> Updated Dockerfile 

Dockerfile
New collection of cyanobacteria secondary metabolites thanks to Lilli at Eawag!
=> New CyanoMetDB database

Dockerfile
=> Updates to CyanoMetDB

.github/workflows/docker-image.yml, .github/workflows/maven.yml, .gitignore, Dockerfile, README.md
*all tests run
*Actions for Maven build and docker build and push
*Update build batch in README to show Actions status
=> Updates on Actions and README

Dockerfile
=> New PCL from end of August

Dockerfile
...latest PCL should now appear second, after COCONUT. Rest are in date order.
=> Adjusted local DB order

Dockerfile
...and reordered wrt COCONUT (now in approx time order).
=> updated to October PubChemLite

Dockerfile
=> Updated PubChemLite to 20230127 version

Dockerfile
...updated Docker file to contain the latest PubChemLite version...
=> Updated to February's PubChemLite

Dockerfile
... and the other OECDPFAS file on Beta is good to go to main MetFrag (somehow the last updates never filtered through...)
=> Updated to March PubChemLite

Dockerfile
...thanks to Lilli Janssen. I adjusted the order to keep our "most recent at top" strategy consistent.
=> Updated CyanoMetDB to 2023 release

Dockerfile
Many thanks in advance @sneumann  ;-) 
As promised, a smaller, more compact version that should improve run times, performance is better than last month, would be great to push this to the main website when you get the chance to ease performance issues if anyone uses older versions.
=> Updated to PCL from May 2023

Dockerfile
Thanks in advance for sending these updates through @sneumann !
(I think I saw the cause of the confused joint April and May appearance last time, hopefully now just one June file appears!)
=> Added June version of PubChemLite

Dockerfile
... in sync with latest version on their website. File contributed by [Bego Talavera Andújar](https://zenodo.org/record/8144127).
=> added latest LIPIDMAPS LMSD

Dockerfile
...with greetings from Munich airport ...
=> Updated PubChemLite to July 2023

Dockerfile
Thanks in advance for merging ;-)
=> PubChemLite - Sept 2023 update

Dockerfile
added "s" to all remaining URLs to avoid redirect issues. Addressing @sneumann 's suggestion here: https://github.com/ipb-halle/MetFragRelaunched/pull/131#issuecomment-1812165898
=> Updating Zenodo URLs

Dockerfile
It's already last Friday of the month again ... here's the latest PCL @sneumann ! :-)
=> Updated PubChemLite to November 2023

Dockerfile
...last update for 2023 for @sneumann to merge, Happy New Year ;-)
=> Dec 2023 PubChemLite

Dockerfile
Here's January's PubChemLite for you @sneumann - Happy New Year!
=> PubChemLite Jan 24 version

Dockerfile
=> Feb 2024 PubChemLite ;-)

Dockerfile
...and a little bit of clean-up of older versions... thanks in advance @sneumann !!
(yes some questions for Dagstuhl are accumulating...)!
=> April PCL & March PCL+CCS

Dockerfile
Added April's PCL + CCS predictions, thanks in advance @sneumann for merging ;-)
=> April's CCSbase PCL

Dockerfile
Thanks in advance @sneumann  ;-)
=> Added May's PCL

Dockerfile
...and May's PubChemLite-CCSbase file. Thanks in advance @sneumann  :-)
=> Added June 2024 PubChemLite

Dockerfile
Thanks in advance for adding @sneumann :-)
=> Added July PubChemLite, June PCL-CCS

Dockerfile
...as requested in https://github.com/ipb-halle/MetFrag/issues/24
@sneumann I have tested this offline in MetFragCL 2.4.5 and it works fine (found some errors which I've resolved, see [Zenodo description](https://zenodo.org/records/13148840)), more recent versions of MetFragCL won't work on my win11 machine (class incompatibility between 52.0 & 55.0 despite upgrading to latest Java). I could not test this on MetFrag Web either normal or Beta, neither would load (any) CSV properly ... :-( 
Let me know when it's on Beta so I can verify it works?
=> Updated NPAtlas to 2024-03 version

Dockerfile
...with Aug CCS to come in a few days time! Thanks in advance @sneumann :-)
=> Updated PCL (Aug 24) and PCL-CCS (Jul 24)

Dockerfile
...and PubChemLite-CCS (Aug '24). Thanks in advance @sneumann !
=> Updated PubChemLite (Sept 24)

Dockerfile
Thanks to Lilli Janssen (Eawag), we have the 2024 (annual update) of CyanoMetDB with hundreds of new entries - I have tested on MetFragCL and MetFrag Web and this should work fine. Thanks in advance @sneumann
=> 2024 version of CyanoMetDB!

Dockerfile
Thanks in advance @sneumann :-)
=> Nov '24 PCL & Oct '24 PCL-CCS

Dockerfile
Thanks in advance @sneumann !
Let me know if I should now be committing to a dev branch instead ...
=> PCL-CCS from Nov '24

Dockerfile
...I had terrible issues with merging conflicts and syncing, I hope this is the right branch @meier-rene @sneumann but it got a lot worse when I tried dev...
=> added Jan '25 PCL & OECD PFAS

Dockerfile
@meier-rene @sneumann I have had terrible trouble syncing my repo and committing (I have had to discard several attempts), it no longer works at all via GitHub Desktop, now I am attempting via the web interface, I hope this works! It says I no longer have permissions via Desktop.
=> Update to March '25 PCL & Feb PCL-CCS

Dockerfile
...which also serves to test whether I can commit painlessly again. @sneumann @meier-rene any idea how I can set `dev` as the default branch on my fork? Thanks in advance!
=> Added March PCL-CCS file

Dockerfile
Updated PubChemLite files ... thanks @meier-rene @sneumann
=> PubChemLite updates

Dockerfile
Thanks in advance for merging @meier-rene @sneumann !
=> Sept PCL & PCL-CCS
